// <auto-generated />
using System;
using EmployeeMgmt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeMgmt.Migrations
{
    [DbContext(typeof(EmployeeMgtContext))]
    partial class EmployeeMgtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeMgmt.Models.Department", b =>
                {
                    b.Property<int>("Deptid")
                        .HasColumnType("int")
                        .HasColumnName("deptid");

                    b.Property<string>("Deptname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("deptname");

                    b.HasKey("Deptid")
                        .HasName("PK__Departme__BE2C1AEE0FD3BC4E");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("EmployeeMgmt.Models.Employee", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime")
                        .HasColumnName("Date_of_joining");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("empId");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Manager")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Phoneno")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Email")
                        .HasName("PK__Employee__A9D10535B7F162A6");

                    b.HasIndex("DeptId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("EmployeeMgmt.Models.EmployeeProject", b =>
                {
                    b.Property<int>("Epid")
                        .HasColumnType("int")
                        .HasColumnName("epid");

                    b.Property<string>("Empemail")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("empemail");

                    b.Property<int?>("ProjId")
                        .HasColumnType("int")
                        .HasColumnName("proj_id");

                    b.HasKey("Epid")
                        .HasName("PK__Employee__3AF3FC78E77C9768");

                    b.HasIndex("Empemail");

                    b.HasIndex("ProjId");

                    b.ToTable("EmployeeProjects");
                });

            modelBuilder.Entity("EmployeeMgmt.Models.Project", b =>
                {
                    b.Property<int>("Projectid")
                        .HasColumnType("int")
                        .HasColumnName("projectid");

                    b.Property<int?>("Did")
                        .HasColumnType("int")
                        .HasColumnName("did");

                    b.Property<DateTime?>("Duration")
                        .HasColumnType("datetime")
                        .HasColumnName("duration");

                    b.Property<string>("Projectname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("projectname");

                    b.HasKey("Projectid")
                        .HasName("PK__Project__11EC39DD241AF5D9");

                    b.HasIndex("Did");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("EmployeeMgmt.Models.Employee", b =>
                {
                    b.HasOne("EmployeeMgmt.Models.Department", "Dept")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK__Employee__dept_i__4E88ABD4");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("EmployeeMgmt.Models.EmployeeProject", b =>
                {
                    b.HasOne("EmployeeMgmt.Models.Employee", "EmpemailNavigation")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("Empemail")
                        .HasConstraintName("FK__EmployeeP__empem__5165187F");

                    b.HasOne("EmployeeMgmt.Models.Project", "Proj")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjId")
                        .HasConstraintName("FK__EmployeeP__proj___52593CB8");

                    b.Navigation("EmpemailNavigation");

                    b.Navigation("Proj");
                });

            modelBuilder.Entity("EmployeeMgmt.Models.Project", b =>
                {
                    b.HasOne("EmployeeMgmt.Models.Department", "DidNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("Did")
                        .HasConstraintName("FK__Project__did__4BAC3F29");

                    b.Navigation("DidNavigation");
                });

            modelBuilder.Entity("EmployeeMgmt.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EmployeeMgmt.Models.Employee", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("EmployeeMgmt.Models.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
